CLARIFICATION_MAP = {
    "jadwal_krs": "Apakah Anda ingin menanyakan tentang tanggal dimulainya periode KRS atau mengenai batas akhir (deadline) pengisiannya?",
    "syarat_krs": "Terkait KRS, apakah yang Anda maksud adalah syarat pelunasan UKT atau mengenai prosedur validasi oleh Dosen Wali?",
    "jadwal_kuliah": "Bisa diperjelas? Apakah Anda mencari jadwal harian per kelas atau tanggal dimulainya perkuliahan perdana?",
    "cek_nilai": "Apakah Anda ingin tahu cara melihat KHS di Siakad atau prosedur untuk memperbaiki nilai yang kurang (E/D)?",
    "jadwal_ujian": "Apakah Anda mencari jadwal pelaksanaan UTS/UAS atau mengenai jadwal untuk ujian susulan?",
    "syarat_ujian": "Mohon maaf, apakah Anda menanyakan syarat kartu ujian fisik atau syarat minimal kehadiran untuk bisa ikut UAS?",
    "info_kalender": "Apakah Anda mencari info tanggal merah/libur nasional atau jadwal penting dalam kalender akademik semester ini?",
    "cuti_kuliah": "Untuk cuti, apakah Anda ingin tahu prosedur pengajuannya atau mengenai batas waktu maksimal diperbolehkan cuti?",
    "aktif_kuliah": "Apakah Anda membutuhkan surat keterangan aktif untuk beasiswa atau untuk keperluan tunjangan orang tua?",
    "pindah_prodi": "Apakah yang Anda maksud adalah prosedur pindah jurusan di dalam kampus atau mengenai konversi nilai dari prodi lama?",
    "syarat_skripsi": "Terkait Skripsi, apakah Anda mencari info minimal SKS yang harus ditempuh atau prasyarat mata kuliah tertentu?",
    "pengajuan_judul": "Apakah Anda mengalami kendala saat input di sistem SITA atau ingin menanyakan format outline judul skripsi?",
    "dosen_pembimbing": "Apakah Anda ingin tahu cara cek nama Dospem di Siakad atau prosedur untuk mengajukan pergantian Dospem?",
    "kerja_praktik": "Terkait Magang/KP, apakah Anda mencari info syarat pendaftaran atau mengenai prosedur surat pengantar ke instansi?",
    "syarat_wisuda": "Bisa diperjelas? Apakah Anda mencari syarat dokumen yudisium atau mengenai validasi bebas tanggungan perpus?",
    "jadwal_wisuda": "Apakah Anda ingin menanyakan tanggal pelaksanaan upacara wisuda atau mengenai jadwal gladi bersihnya?",
    "biaya_wisuda": "Apakah Anda menanyakan nominal total biaya wisuda atau rincian pembayaran untuk toga dan ijazah?",
    "legalisir_ijazah": "Apakah Anda ingin melakukan legalisir secara online melalui aplikasi atau datang langsung ke loket BAA?",
    "sertifikat_toefl": "Apakah Anda mencari informasi skor minimal ELPT untuk syarat kelulusan atau mengenai jadwal tes terdekat?",
    "beas_pustaka": "Apakah Anda ingin tahu cara upload file ke Repository atau mengenai syarat sumbangan buku ke perpustakaan?",
    "biaya_ukt": "Apakah Anda mencari informasi nominal UKT per prodi atau mengenai rincian tagihan yang muncul di akun Siakad?",
    "cara_bayar_ukt": "Apakah Anda butuh panduan bayar lewat Mobile Banking (BNI/Jatim) atau melalui teller Bank secara langsung?",
    "dispensasi_bayar": "Apakah Anda ingin mengajukan penundaan pembayaran atau mekanisme cicilan UKT karena kendala biaya?",
    "denda_ukt": "Apakah Anda ingin tahu besaran denda telat bayar atau cara mengaktifkan kembali akun Siakad yang terblokir?",
    "potongan_ukt": "Apakah Anda menanyakan diskon untuk saudara kandung (kakak-adik) atau mengenai beasiswa potongan UKT lainnya?",
    "lupa_password": "Akun mana yang bermasalah? Apakah password Siakad, Email mahasiswa, atau login Wi-Fi kampus?",
    "ganti_data": "Data apa yang ingin diperbaiki? Apakah kesalahan ejaan nama, tanggal lahir, atau update nomor telepon?",
    "siakad_error": "Apakah Anda mengalami kendala 'Session Expired', halaman putih (blank), atau gagal login ke Siakad?",
    "lokasi_gedung": "Gedung mana yang Anda cari? Saya bisa menunjukkan lokasi Graha Cendekia, Lab Terpadu, atau ruang TU.",
    "info_wifi": "Apakah Anda kesulitan login ke Wi-Fi kampus atau ingin menanyakan password area perpustakaan?",
    "jam_perpus": "Apakah Anda ingin tahu jam operasional harian atau jadwal pelayanan validasi bebas pustaka?",
    "lokasi_masjid": "Apakah Anda mencari Masjid Ulul Albab atau mushola terdekat dari gedung perkuliahan Anda?",
    "lokasi_kantin": "Apakah Anda mencari lokasi kantin pusat (food court) atau tempat makan terdekat dari area parkir?",
    "info_beasiswa": "Beasiswa mana yang Anda maksud? KIP-Kuliah, Beasiswa PPA, atau bantuan biaya dari Pemda?",
    "info_kkn": "Terkait KKN, apakah Anda menanyakan jadwal pendaftarannya atau mengenai rincian wilayah penempatan?",
    "organisasi_kampus": "Apakah Anda ingin bergabung dengan BEM universitas, Himpunan Mahasiswa (Hima), atau Unit Kegiatan Mahasiswa (UKM)?",
    "klinik_kesehatan": "Apakah Anda membutuhkan pelayanan dokter di Poliklinik atau mencari lokasi UKS untuk kondisi darurat?",
    "sapaan": "Halo! Saya asisten virtual akademik UNIPMA. Ada yang bisa saya bantu terkait info perkuliahan Anda?",
    "identitas_bot": "Saya adalah AI yang dirancang untuk membantu informasi akademik. Anda ingin tahu lebih lanjut tentang pengembang saya?",
    "pamit": "Sama-sama! Senang bisa membantu. Apakah ada hal lain yang ingin Anda tanyakan sebelum saya tutup?"
}